#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

command="make all -j"
echo "Executing local ci checks before push"
$command
result=$?
if [ "$result" -ne 0 ]; then
 echo "Failed execution of tests"
 exit 1
fi
exit 0